### ISSUE TITLE
Handling of Challenges Requiring Different User Privileges

### ISSUE THREAD

**Issue by prathamgupta36** [pwncollege/ctf-archive#5]
Some challenges in our environment require users to have different privilege levels to execute certain binaries or scripts. We should find a way to give the user the privileges without compromising the integrity of the challenge.

**Comment by zardus** [comment]
Some options:

1. Configure sudo to give this access (e.g., `sudo -u stage1`). This could be done in `.init` or as a function of the platform itself. Probably the cleanest route would be to make it so that a `/challenge/.sudoers` file is automatically included by `/etc/sudoers`.
2. Have suid binaries `/challenge/stage1`, `/challenge/stage2`, and so on that set the right privs.

**Comment by prathamgupta36** [comment]
I tried something like this in the .init file to give privileges:
```
echo "username ALL=(ALL) NOPASSWD: /challenge/zerofs" >> /etc/sudoers.d/ctf_zerofs
chmod 440 /etc/sudoers.d/ctf_zerofs
```
This did not work so I am trying to troubleshoot.

**Comment by zardus** [comment]
Sudo is disabled outside of practice mode by removing its suid bit. If you
want to re-enable it, you gotta `chmod 4755 usr/bin/sudo`.

**Comment by prathamgupta36** [comment]
That worked and now hacker has the permission to run just the challenge but only if they use `sudo` before `/challenge/name`. Should I make another binary that works without the sudo or a note in the challenge description should be enough.

**Comment by zardus** [comment]
I think sudo should be enough

**Comment by prathamgupta36** [comment]
Sounds good, the `.init` can be used as template for any future challenges requiring special privileges.
